package testXr;
// Generated May 18, 2015 3:59:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;


/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String email;
	private String name;
	private String password;
	private boolean enable;
	private Set<Roles> roleses = new HashSet<Roles>(0);
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public boolean isEnable() {
		return enable;
	}
	public void setEnable(boolean enable) {
		this.enable = enable;
	}
	public Set<Roles> getRoleses() {
		return roleses;
	}
	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
